// -----------------------------------------------------------------------------
// Zendure cloud API client.
//
// Ported from the Zendure service of Gladys core (zendure.connect.js +
// zendure.discoverDevices.js), reshaped for the integration SDK: pure
// functions, no service status machine, injectable `fetch` for tests.
//
// Protocol facts (validated against the real cloud):
//   - The "cloud key" (authorization key) is a base64 token that decodes to
//     `<apiUrl>.<appKey>` (the LAST dot separates the two parts).
//   - The device list comes from `POST {apiUrl}/api/ha/deviceList` with the
//     JSON body `{ appKey }`.
//   - Requests carry signed headers: timestamp, nonce, clientid=zenHa and
//     sign=SHA1(SIGN_KEY + sorted(appKey,nonce,timestamp) + SIGN_KEY).
//   - The response also carries the cloud MQTT broker metadata (`data.mqtt`),
//     used later for real-time telemetry.
// -----------------------------------------------------------------------------

import crypto from 'node:crypto';
import { createLogger } from '@gladysassistant/integration-sdk';

import { API, AUTH } from './constants.js';

const logger = createLogger({ name: 'zendure-client' });

/** Error thrown for every Zendure cloud problem (bad key, HTTP or API error). */
export class ZendureCloudError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ZendureCloudError';
  }
}

/**
 * Decode the Zendure cloud key and split API URL / app key.
 * @param {string} cloudKey base64 token generated by the Zendure mobile app
 * @returns {{ apiUrl: string, appKey: string }}
 */
export function decodeCloudKey(cloudKey) {
  if (!cloudKey || typeof cloudKey !== 'string' || cloudKey.trim().length < 5) {
    throw new ZendureCloudError('Zendure cloud key is missing.');
  }

  const decoded = Buffer.from(cloudKey.trim(), 'base64').toString('utf8');
  if (!decoded || !decoded.includes('.')) {
    throw new ZendureCloudError('Zendure cloud key format is invalid.');
  }

  const lastDot = decoded.lastIndexOf('.');
  if (lastDot <= 0 || lastDot === decoded.length - 1) {
    throw new ZendureCloudError('Zendure cloud key format is invalid.');
  }

  return {
    apiUrl: decoded.slice(0, lastDot),
    appKey: decoded.slice(lastDot + 1),
  };
}

/**
 * Build the signed request headers expected by the Zendure cloud API.
 * `timestamp` (seconds) and `nonce` are injectable for deterministic tests.
 * @param {string} appKey Zendure app key
 * @param {{ timestamp?: number, nonce?: string }} [options]
 * @returns {Record<string, string>}
 */
export function buildSignedHeaders(appKey, { timestamp, nonce } = {}) {
  const ts = timestamp ?? Math.floor(Date.now() / 1000);
  const n = nonce ?? `${Math.floor(Math.random() * 90000) + 10000}`;

  const signParams = { appKey, timestamp: ts, nonce: n };
  const bodyStr = Object.keys(signParams)
    .sort()
    .map((key) => `${key}${signParams[key]}`)
    .join('');
  const signStr = `${AUTH.SIGN_KEY}${bodyStr}${AUTH.SIGN_KEY}`;
  const sign = crypto.createHash('sha1').update(signStr, 'utf8').digest('hex').toUpperCase();

  return {
    'Content-Type': 'application/json',
    timestamp: `${ts}`,
    nonce: n,
    clientid: AUTH.CLIENT_ID,
    sign,
  };
}

/**
 * Fetch the Zendure cloud payload: the device list and the MQTT broker
 * metadata. Validates the response shape and throws ZendureCloudError on any
 * authentication or contract problem.
 * @param {string} cloudKey base64 cloud key from the configuration
 * @param {{ fetchImpl?: typeof fetch }} [options] injectable fetch for tests
 * @returns {Promise<{ deviceList: Array<object>, mqtt: object }>}
 */
export async function fetchCloudData(cloudKey, { fetchImpl = fetch } = {}) {
  const { apiUrl, appKey } = decodeCloudKey(cloudKey);
  const headers = buildSignedHeaders(appKey);

  logger.debug(`Connecting to Zendure cloud (${apiUrl})...`);

  const response = await fetchImpl(`${apiUrl}${API.DEVICE_LIST}`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ appKey }),
  });

  if (response.status >= 400) {
    throw new ZendureCloudError(`Zendure cloud request failed (HTTP ${response.status}).`);
  }

  const body = await response.json();
  if (!body || !body.success || body.code !== 200 || !body.data) {
    const cloudCode = body && body.code !== undefined ? body.code : 'unknown';
    const cloudMessage = (body && (body.msg || body.message)) || 'unknown error';
    throw new ZendureCloudError(
      `Zendure cloud authentication failed (code=${cloudCode}, message=${cloudMessage}).`,
    );
  }

  const { data } = body;
  if (!Array.isArray(data.deviceList)) {
    throw new ZendureCloudError('Zendure cloud response is invalid: device list is missing.');
  }
  if (data.deviceList.length === 0) {
    throw new ZendureCloudError(
      'Zendure cloud authentication failed: no device found for this key.',
    );
  }
  if (!data.mqtt || typeof data.mqtt !== 'object' || Object.keys(data.mqtt).length === 0) {
    throw new ZendureCloudError('Zendure cloud authentication failed: MQTT metadata is missing.');
  }

  logger.debug(`Zendure cloud returned ${data.deviceList.length} device(s).`);
  return data;
}
